### ISSUE TITLE
[Bug] HA is deprecating async_forward_entry_setup

### ISSUE THREAD

**Issue by mrussak** [SecKatie/ha-wyzeapi#626] opened 2024-09-02 17:21 UTC
**Describe the bug**
HA is deprecating `async_forward_entry_setup`, which appears to be used in this integration.

**To Reproduce**

Using HA 2024.8.3:
Allow HA to startup, then examine HA logs:
```
2024-09-02 10:15:08.850 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration, wyzeapi with title: and entry_id: 157586b3d894fb191b500f412a83bf38, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
```

**System configuration**
System: Docker running on RaspberryPi 4
HA Version: 0.1.27
WyzeApi Version: 2024.8.3

**Comment by brg468** [comment] 2024-09-02 17:29
Duplicate of https://github.com/SecKatie/ha-wyzeapi/issues/623 and a fix is already waiting to be pushed.

**Closed by brg468** 2024-09-02 17:29 UTC
Labels: bug
