### ISSUE TITLE
Why is notification switch?

### ISSUE THREAD

**Issue by mikefrantz** [SecKatie/ha-wyzeapi#578] opened 2024-05-04 21:25 UTC
**Describe the bug**
The Wyze notification switch in Home Assistant, no longer arms or disarm the notifications

**To Reproduce**

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment] 2024-05-04 22:00
Duplicate of https://github.com/SecKatie/ha-wyzeapi/issues/570

**Closed by brg468** 2024-05-04 22:00 UTC
Labels: bug

**Comment by mikefrantz** [comment] 2024-05-04 23:26
Thanks for getting back with me so quickly. And I do appreciate all the work you do on this project. I apologize I do not know how to get to the duplicate 570 or 578. Can you guide me please?Thanks MikeOn May 4, 2024, at 6:00 PM, Brian Rogers ***@***.***> wrote:﻿
Duplicate of #570

**Comment by brg468** [comment] 2024-05-04 23:31
I’m not exactly sure what you’re asking for. This is 578, which I closed because it’s a dupe of 570. The link above gets you to 570, or it’s under issues. In any case I’m aware it’s an issue but haven’t had time to investigate so far.

**Comment by mikefrantz** [comment] 2024-05-04 23:33
Thanks again for all your hard work and effort keeping this up and running. We really do enjoy your work.Thanks MikeOn May 4, 2024, at 7:32 PM, Brian Rogers ***@***.***> wrote:﻿
I’m not exactly sure what you’re asking for. This is 578, which I closed because it’s a dupe of 570. The link above gets you to 570, or it’s under issues. In any case I’m aware it’s an issue but haven’t had time to investigate so far.
